services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/base:ubuntu
    volumes:
      - ../..:/workspaces:cached
    #network_mode: service:portainer
    command: sleep infinity
  
  #portainer:
  #  image: portainer/portainer-ce:latest
  #  restart: unless-stopped
  #  ports:
  #    - "9000:9000"
  #    - "9443:9443"
  #  volumes:
  #    - /var/run/docker.sock:/var/run/docker.sock
  #    - portainer_data:/data

#volumes:
#  portainer_data: